site_name: ros2_pcl_ws
site_url: https://andresislas99.github.io/ros2_pcl_ws/
repo_url: https://github.com/AndresIslas99/ros2_pcl_ws
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
nav:
  - Overview: docs/OVERVIEW.md
  - Install: docs/INSTALL.md
  - Environment: docs/ENVIRONMENT.md
  - Build: docs/BUILD.md
  - Usage: docs/USAGE.md
  - Troubleshooting: docs/TROUBLESHOOTING.md
  - CI: docs/CI.md
  - GitHub: docs/GITHUB.md
