name: ci
on:
  push:
  pull_request:
jobs:
  build-test:
    strategy:
      matrix:
        ros_distro: [jazzy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: pointcloud_play
          target-ros2-distro: ${{ matrix.ros_distro }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          vcs-repo-file-url: ""
