name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ROS Humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      # CI para 1 solo paquete dentro del repo, sin importar repos externos
      - name: Build with action-ros-ci (no VCS import)
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          package-name: pointcloud_play
          skip-tests: true
          # Fuerza a NO usar archivos .repos/.repo externos
          vcs-repo-file-url: ""

